server:
  port: 8888

#数据源配置
spring:
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3307/video?serverTimezone=Asia/Shanghai
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

#MyBatis配置
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.li.demo4.entity
  configuration:
    map-underscore-to-camel-case: true

